//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnTotNghiep.Model
{
    using DoAnTotNghiep.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class bonu : BaseViewModel
    {
        public int id { get; set; }
        public System.DateTime createdAt { get; set; }
        private Nullable<System.DateTime> _updatedAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get => _updatedAt; set { _updatedAt = value; OnPropertyChanged(); } }
        public int createdBy { get; set; }
        private Nullable<int> _updatedBy;
        public Nullable<int> updatedBy { get => _updatedBy; set { _updatedBy = value; OnPropertyChanged(); } }
        private string _reason;
        public string reason { get => _reason; set { _reason = value; OnPropertyChanged(); } }
        private int _bonus;
        public int bonus { get => _bonus; set { _bonus = value; OnPropertyChanged(); } }
        private int _teacherId { get; set; }
        public int teacherId { get => _teacherId; set { _teacherId = value; OnPropertyChanged(); } }

        public virtual teacher teacher { get; set; }
    }
}
