//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnTotNghiep.Model
{
    using DoAnTotNghiep.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class @class : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public @class()
        {
            this.students_classes = new HashSet<students_classes>();
            this.teacher_class = new HashSet<teacher_class>();
        }

        public int id { get; set; }
        public System.DateTime createdAt { get; set; }
        private Nullable<System.DateTime> _updatedAt;
        public Nullable<System.DateTime> updatedAt { get => _updatedAt; set { _updatedAt = value; OnPropertyChanged(); } }
        public int createdBy { get; set; }
        private Nullable<int> _updatedBy;
        public Nullable<int> updatedBy { get => _updatedBy; set { _updatedBy = value; OnPropertyChanged(); } }
        private string _class1;
        public string class1 { get => _class1; set { _class1 = value; OnPropertyChanged(); } }
        private System.TimeSpan _startTime;
        public System.TimeSpan startTime { get => _startTime; set { _startTime = value; OnPropertyChanged(); } }

        private System.TimeSpan _endTime;
        public System.TimeSpan endTime { get => _endTime; set { _endTime = value; OnPropertyChanged(); } }
        private byte _status;
        public byte status { get => _status; set { _status = value; OnPropertyChanged(); } }
        private int _semesterId;
        public int semesterId { get => _semesterId; set { _semesterId = value; OnPropertyChanged(); } }

        public virtual semester semester { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<students_classes> students_classes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teacher_class> teacher_class { get; set; }
    }
}
