//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnTotNghiep.Model
{
    using DoAnTotNghiep.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class exercise : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public exercise()
        {
            this.homework_student = new HashSet<homework_student>();
        }
    
        public int id { get; set; }
        private Nullable<System.DateTime> _updatedAt;
        private Nullable<int> _updatedBy;
        private string _Title;
        private string _fileName;
        private System.DateTime _startDate;
        private System.DateTime _dueDate;
        private byte _status;
        private int _classesTeacherId;
        public System.DateTime createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get => _updatedAt; set { _updatedAt = value; OnPropertyChanged(); } }
        public int createdBy { get; set; }
        public Nullable<int> updatedBy { get => _updatedBy; set { _updatedBy = value; OnPropertyChanged(); } }
        public string Title { get => _Title; set { _Title = value; OnPropertyChanged(); } }
        public string fileName { get => _fileName; set { _fileName = value; OnPropertyChanged(); } }
        public System.DateTime startDate { get => _startDate; set { _startDate = value; OnPropertyChanged(); } }
        public System.DateTime dueDate { get => _dueDate; set { _dueDate = value; OnPropertyChanged(); } }
        public byte status { get => _status; set { _status = value; OnPropertyChanged(); } }
        public int classesTeacherId { get => _classesTeacherId; set { _classesTeacherId = value; OnPropertyChanged(); } }
    
        public virtual teacher_class teacher_class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<homework_student> homework_student { get; set; }
    }
}
