//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnTotNghiep.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class parent
    {
        public int id { get; set; }
        public System.DateTime createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
        public int createdBy { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public string dadName { get; set; }
        public string dadPhone { get; set; }
        public string momName { get; set; }
        public string momPhone { get; set; }
        public int studentId { get; set; }
        public int usersId { get; set; }
    
        public virtual student student { get; set; }
        public virtual user user { get; set; }
    }
}
